version: '3'
services:
  db:
    image: postgres
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data #MacOSの場合
    environment:
      POSTGRES_USER: 'top_app_dev'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DATABASE: 'top_app_db'
    restart: always

  web:
    build: .
    command: /bin/sh -c "rm -f /app_name/tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    tty: true
    volumes:
      - .:/app_name
    ports:
      - "3000:3000"
    links:
      - db